### Variables
@baseUrl = http://localhost:5000/api
@scholarId = {{createScholar.response.body.data._id}}

### 1. Create a New Scholar
# @name createScholar
POST {{baseUrl}}/scholars
Content-Type: application/json

{
    "name": "Isko Salvador",
    "studentNumber": "2021-04567",
    "program": "BS Applied Mathematics",
    "upMail": "isalvador@up.edu.ph",
    "scholarshipStartDate": "2021-08-15",
    "status": "Student"
}

###

### 2. Get All Scholars
GET {{baseUrl}}/scholars
Accept: application/json

###

### 3. Update Scholar Status (Graduated)
PUT {{baseUrl}}/scholars/{{scholarId}}
Content-Type: application/json

{
    "status": "Graduated"
}

###

### 4. Delete a Scholar
DELETE {{baseUrl}}/scholars/{{scholarId}}

###

### 5. Test Validation (Should Fail - Not @up.edu.ph)
POST {{baseUrl}}/scholars
Content-Type: application/json

{
    "name": "Invalid Email Test",
    "studentNumber": "2022-00000",
    "program": "BA History",
    "upMail": "test@gmail.com",
    "scholarshipStartDate": "2022-09-01"
}